model:
  name: 'osnet_x1_0'
  pretrained: False

data:
  type: 'image'
  root: '/remote-home/my/code/TRSOSNet/data/'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_erase']
  save_dir: 'log/trsosnet_dukemtmcreid'

sampler:
  train_sampler: RandomSampler


loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'sgd'
  lr: 0.065
  max_epoch: 350
  batch_size: 64
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'multi_step'
  stepsize: [150, 225, 300]
  gamma: 0.1


test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: True
  visrank: False